version: '2'
services:
  nginx:
      build: ./nginx/
      ports:
          - 80:80
      links:
          - php
      volumes_from:
          - app
      container_name: service_nginx
  php:
      build: ./php/
      expose:
          - 9000
      links:
          - mysql
      volumes_from:
          - app
      container_name: service_php
  mysql:
      image: mysql:latest
      volumes_from:
          - data
      ports:
          - 3306:3306
      environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: pharmacie
          MYSQL_USER: root
          MYSQL_PASSWORD: root
      container_name: service_mysql
  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      ports:
          - 8080:80
      links:
          - mysql
      environment:
          PMA_HOST: mysql
      container_name:
        service_pma
  app:
      image: php:7.0-fpm
      volumes:
          - /home/docker/service/app:/var/www/html
      command: "true"
  data:
      image: mysql:latest
      volumes:
          - /home/docker/mysql
      command: "true"
